"""add session_uuid in session table

Revision ID: b0396069b9c6
Revises: a83b9f454102
Create Date: 2024-09-29 21:09:11.864581

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b0396069b9c6"
down_revision: Union[str, None] = "a83b9f454102"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions", sa.Column("session_uuid", sa.String(), nullable=False)
    )
    op.create_unique_constraint(None, "sessions", ["session_uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sessions", type_="unique")
    op.drop_column("sessions", "session_uuid")
    # ### end Alembic commands ###
