"""add is_deactivated field in session table

Revision ID: a83b9f454102
Revises: 803699125fa8
Create Date: 2024-09-29 18:20:48.091515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a83b9f454102"
down_revision: Union[str, None] = "803699125fa8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions",
        sa.Column(
            "is_deactivated",
            sa.Boolean(),
            server_default="False",
            nullable=False,
        ),
    )
    op.add_column(
        "sessions",
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "expires_at")
    op.drop_column("sessions", "is_deactivated")
    # ### end Alembic commands ###
