"""rename fields in users table

Revision ID: d31b63456801
Revises: 67b4c2e3b724
Create Date: 2024-09-24 16:33:37.709022

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d31b63456801"
down_revision: Union[str, None] = "67b4c2e3b724"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("firstName", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "users", sa.Column("lastName", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "users", sa.Column("hashed_password", sa.LargeBinary(), nullable=False)
    )
    op.drop_constraint("users_firstname_key", "users", type_="unique")
    op.drop_constraint("users_last_name_key", "users", type_="unique")
    op.drop_column("users", "hash_password")
    op.drop_column("users", "last_name")
    op.drop_column("users", "firstname")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "firstname",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "last_name",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "hash_password",
            postgresql.BYTEA(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_unique_constraint("users_last_name_key", "users", ["last_name"])
    op.create_unique_constraint("users_firstname_key", "users", ["firstname"])
    op.drop_column("users", "hashed_password")
    op.drop_column("users", "lastName")
    op.drop_column("users", "firstName")
    # ### end Alembic commands ###
