"""add is_confirmed field to User_emails table

Revision ID: 8cd7c9fdcf7a
Revises: 1693babb1ede
Create Date: 2024-10-13 13:39:54.650175

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8cd7c9fdcf7a"
down_revision: Union[str, None] = "1693babb1ede"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_emails",
        sa.Column(
            "is_confirmed",
            sa.Boolean(),
            server_default="False",
            nullable=False,
        ),
    )
    op.create_unique_constraint(None, "user_emails", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_emails", type_="unique")
    op.drop_column("user_emails", "is_confirmed")
    # ### end Alembic commands ###
